spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest  
    
security:
  oauth2:
    client:
      clientId: webApp
      clientSecret: 123456
      access-token-uri: http://localhost:9000/uac/oauth/token
      user-authorization-uri: http://localhost:9000/uac/oauth/authorize
    resource:
      user-info-uri: http://localhost:9000/uac/user
